0.0.2a

diff --git a/lcget b/lcget
--- a/lcget
+++ b/lcget
@@ -1,4 +1,21 @@
 #!/usr/bin/expect --
+
+#####################################################################
+# Coding conventions:
+# * Error message must start with 'E: ' and end with 'Abort.'
+#
+#####################################################################
+
+set p_name      "lcget"
+set p_author    "Md. Jahidul Hamid"
+set p_author_eu "jahidulhamid"
+set p_author_ed "yahoo.com"
+set p_version   "0.0.2a"
+set p_source    "https://github.com/neurobin/lcget"
+set p_bugt      "$p_source/issues"
+set jssh_link   "https://github.com/neurobin/jssh"
+
+set help "
 #####################################################################
 # Let's Encrypt wrapper to automate the process of completing
 # challenges to get free SSL certificates from Let's Encrypt.
@@ -7,18 +24,46 @@
 # and depends on letsencrypt to run those commands and finally
 # Get the certificates. All this script does is to complete the
 # challenges using ssh login to remote server.
-# 
-#Options:
-# 
-# -lp /path/to/letsencrypt/launcher : If this option is not given
-#       It will assume 'letsencrypt' as the name of the launcher
-#       and it resides on a standard bin directory in your system.
 #
+# Usage:
+#  $p_name \[native and/or letsencrypt options/args]
+# 
+# Native options:
+# 
+#  -lp /path/to/letsencrypt/launcher : If this option is not given
+#       It will assume 'letsencrypt' as the name of the launcher
+#       and it resides in a path in PATH environment
+#       variable in your system.
+#
+#  -jp /path/to/jssh : If this option is not given it will be 
+#       assumed that jssh is in a path in PATH environment
+#       variable in your system i.e 'jssh' command will be 
+#       used by default
 #####################################################################
+"
+
+set verinfo "
+Name:           $p_name
+Version:        $p_version
+Source:         $p_source
+Bug report:     $p_bugt
+Author:         $p_author
+
+Author email:
+    username:   $p_author_eu
+      domain:   $p_author_ed
+"
+
+set err_api_change "
+It seems Let's Encrypt api has gone through some changes.
+Please update this script and if you get this error again,
+then file a bug report at $p_bugt
+with all available outputs/logs.
+"
 
 
 #####################################################################
-proc get_ssh_command {dom cdir cont} {
+proc get_ssh_command_for_http_challenge {dom cdir cont} {
     if {$dom == ""} {
         puts "E: Couldn't parse domain. Abort."
         exit 1
@@ -34,18 +79,18 @@ proc get_ssh_command {dom cdir cont} {
     
     set comms "echo 'Completing challenge...'
     if mkdir -p '$cdir'; then
-        echo 'Created dir: $cdir'
+        echo 'Created dir $cdir'
         if cd '$cdir';then
-            echo 'cd to dir: $cdir'
+            echo 'cd to dir $cdir'
             if echo -n '$cont' >index.html;then
                 echo 'Created index.html'
-                printf 'Challenge completed on:'
+                printf 'Challenge completed on '
                 dirname \`pwd\`
             else
-                echo 'Failed to write file. Abort.'
+                echo 'E: Failed to write file. Abort.'
             fi
         else
-            echo 'cd to $cdir failed. Abort.'
+            echo 'E: cd to $cdir failed. Abort.'
         fi
     else
         echo 'E: Could not create directory. Abort.'
@@ -62,6 +107,7 @@ set timeout -1
 #exp_internal 1
 
 set program "letsencrypt"
+set ssh_prog "jssh"
 set arguments [lrange $argv 0 end]
 
 #Check for no-args
@@ -96,6 +142,21 @@ for {set var 0} {$var<$argc} {incr var} {
             exit 1
         }
     }
+    if {[lindex $arguments $var] == "-jp" || [lindex $arguments $var] == "--jssh-path"} {
+        if {[lindex $arguments [expr {$var+1}]] != ""} {
+            set ssh_prog [lindex $arguments [expr {$var+1}]]
+            set arguments [lreplace $arguments $var [expr {$var+1}]]
+        } else {
+            puts "E: Argument missing for option: [lindex $arguments $var]"
+            exit 1
+        }
+    }
+    if {[lindex $arguments $var] == "-h" || [lindex $arguments $var] == "--help"} {
+        puts "$help"
+    }
+    if {[lindex $arguments $var] == "--version"} {
+        puts "$verinfo"
+    }
 }
 
 if {[catch {spawn -noecho $program --text {*}$arguments}]} {
@@ -114,29 +175,56 @@ while {1} {
         -nocase "*http*.well-known*acme-challenge*http*server*configured*continue" {
             set output $expect_out(buffer)
             set found [regexp  {^.*(https?://)([^/]*)/([^[:space:]]*)[^:]*:[[:space:]]*([^[:space:]]*)} $output match protocol domain dir cont]
-            puts "\n\nProtocol: $protocol\nDomain: $domain\nDir: $dir\nContent: $cont\n"
-            set comms [get_ssh_command $domain $dir $cont]
-            spawn -noecho jssh -cdw $domain $comms
+            if {$found} {
+                puts "\n\nProtocol: $protocol\nDomain: $domain\nDir: $dir\nContent: $cont\n"
+            } else {
+                puts "\n\nCouldn't get challenge info.$err_api_change\n"
+                exit 1
+            }
+            exp_send_user "Trying to complete challenge for $domain\n\n"
+            set comms [get_ssh_command_for_http_challenge $domain $dir $cont]
+            
+            set timeout 60
+            if {[catch {spawn -noecho $ssh_prog -cdw $domain $comms}]} {
+                puts "E: $ssh_prog command not found.\nIs jssh installed? If not then install it from $jssh_link"
+                exit 1
+            }
+            
             set jssh_spawn $spawn_id
+            
             while {1} {
                 expect  {
                     timeout { exp_send_user "\nFailed!!!. Timed out.\n"; exit 1}
                     eof {break}
-                    -nocase "*password" {
-                        stty -echo
-                        exp_send_user -- ""
-                        expect_user -re "(.*)\n"
-                        #exp_send_user "\n"
-                        stty echo
-                        set password $expect_out(1,string)
-                        exp_send "$password\r"
+                    -re "^.\{6,\}$" {#Should be at least 6 in regards of 'ssh: ' for catching unknown prompts
+                        set jssh_output $expect_out(buffer)
+                        #puts $jssh_output
+                        if {[regexp  {^.*password} $jssh_output match]} {
+                            stty -echo
+                            exp_send_user -- ""
+                            expect_user -re "(.*)\n"
+                            #exp_send_user "\n"
+                            stty echo
+                            set password $expect_out(1,string)
+                            exp_send "$password\r"
+                        } elseif {[regexp {^E:.*Abort} $jssh_output match]} {
+                            exp_send_user "\nFailed to complete challenge for $domain\n"
+                            exit 1
+                        } elseif {[regexp {^.\{6,\}[:?][[:space:]]*$} $jssh_output match]} {#catching unknown prompts
+                            expect_user -re "(.*)\n"
+                            set password $expect_out(1,string)
+                            exp_send "$password\r"
+                        }
                     }
                 }
             }
-            exp_close $spawn_id
+            exp_send_user "\nDone for $domain\n"
+            set timeout -1
+            if {[catch {exp_close $jssh_spawn}]} {
+                #spawn was already closed
+            }
             set spawn_id $letse_spawn
             exp_send "\r"
-            exp_send_user "\nCompleted challenge for $domain  \n"
         }
         -nocase "*password" {
             stty -echo
@@ -147,7 +235,7 @@ while {1} {
             set password $expect_out(1,string)
             exp_send "$password\r"
         }
-        -nocase "*terms of service*:" {
+        -nocase "*terms of service*\n*:" {
             exp_send_user -- ""
             expect_user -re "(.*)\n"
             set password $expect_out(1,string)
@@ -159,8 +247,21 @@ while {1} {
             set password $expect_out(1,string)
             exp_send "$password\r"
         }
+        -nocase "*--------------*\n*--------------*:*" {
+            exp_send_user -- ""
+            expect_user -re "(.*)\n"
+            set password $expect_out(1,string)
+            exp_send "$password\r"
+        }
+        -nocase "*--------------*\n*--------------*Press Enter to Continue" {
+            exp_send_user -- ""
+            expect_user -re "(.*)\n"
+            set password $expect_out(1,string)
+            exp_send "$password\r"
+        }
     }
 }
+
 
 
 #Clearing step, Finally close the spawns
